# spring的配置
spring:
  # 数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bntang-his?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    # 注入数据源的类型,默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        allow:
        deny:
        url-pattern: /druid/*
        # 启用数据源监控
        enabled: true
# mybatis-plus的配置
mybatis-plus:
  configuration:
    # SQL控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper.xml文件的扫描
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      # id生成策略
      id-type: auto
# dubbo的配置
dubbo:
  application:
    # 服务名称
    name: his-doctor-service
  registry:
    # 注册地址
    address: zookeeper://39.106.71.75:2181
  protocol:
    # 随机端口
    port: -1
    name: dubbo
  scan:
    # 扫描的包
    base-packages: com.it6666.service.impl
